name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Build and Test SampleApp"] # Must match the 'name' of ci-build-test.yml
    types: [completed]
    branches-ignore:
      - 'main' # Ignore runs from the main branch for this trigger

  push:
    branches:
      - 'main' # Trigger for pushes (merges) to the main branch

jobs:
  # Scenario 1: Deploy to DEV from successful CI on a feature branch
  deploy_dev_from_feature_ci:
    name: Deploy Dev (Feature Branch CI)
    if: |
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch != 'main'
    uses: InwardEcho/.github/.github/workflows/org-environment-orchestrator.yml@main
    with:
      environment_name: 'dev'
      application_name: 'SampleApp'
      app_build_artifact_name_pattern: 'SampleApp-deployment-package'
      app_build_artifact_run_id: ${{ github.event.workflow_run.id }} # Use the run_id of the completed CI workflow

      iac_working_directory: './infra'
      iac_variables_file_path_pattern: './infra/{env}.tfvars'
      iac_backend_config_file_path_pattern: './infra/{env}.backend.hcl'
      iac_azure_credentials_secret_name: 'AZURE_CREDENTIALS_TF_INPUT' # Input for orchestrator

      db_migration_efcore_project_path: './src/SampleApp.WebApp'
      db_connection_string_source: 'keyVault'
      db_azure_credentials_secret_name_for_kv: 'AZURE_CREDENTIALS_KV_INPUT' # Input for orchestrator

      app_deploy_azure_credentials_secret_name: 'AZURE_CREDENTIALS_APP_INPUT' # Input for orchestrator
      version_tag: 'feat-${{ github.event.workflow_run.head_branch }}-${{ github.event.workflow_run.head_sha }}'
    secrets:
      # Secrets this CD workflow provides to the orchestrator for this job
      AZURE_CREDENTIALS_TF_INPUT: ${{ secrets.AZURE_CREDENTIALS_TF_DEV }}
      AZURE_CREDENTIALS_KV_INPUT: ${{ secrets.AZURE_CREDENTIALS_KV_DEV }}
      AZURE_CREDENTIALS_APP_INPUT: ${{ secrets.AZURE_CREDENTIALS_APP_DEV }}

  # Scenario 2: Sequential deployment for pushes to main branch
  deploy_dev_from_main_push:
    name: Deploy Dev (Main Branch)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: InwardEcho/.github/.github/workflows/org-environment-orchestrator.yml@main
    with:
      environment_name: 'dev'
      application_name: 'SampleApp'
      app_build_artifact_name_pattern: 'SampleApp-deployment-package'
      app_build_source_branch: 'main' # Orchestrator's resolve_artifact job should find the latest from main

      iac_working_directory: './infra'
      iac_variables_file_path_pattern: './infra/{env}.tfvars'
      iac_backend_config_file_path_pattern: './infra/{env}.backend.hcl'
      iac_azure_credentials_secret_name: 'AZURE_CREDENTIALS_TF_INPUT'

      db_migration_efcore_project_path: './src/SampleApp.WebApp'
      db_connection_string_source: 'keyVault'
      db_azure_credentials_secret_name_for_kv: 'AZURE_CREDENTIALS_KV_INPUT'

      app_deploy_azure_credentials_secret_name: 'AZURE_CREDENTIALS_APP_INPUT'
      version_tag: 'main-${{ github.sha }}'
    secrets:
      AZURE_CREDENTIALS_TF_INPUT: ${{ secrets.AZURE_CREDENTIALS_TF_DEV }}
      AZURE_CREDENTIALS_KV_INPUT: ${{ secrets.AZURE_CREDENTIALS_KV_DEV }}
      AZURE_CREDENTIALS_APP_INPUT: ${{ secrets.AZURE_CREDENTIALS_APP_DEV }}

  deploy_test_from_main_push:
    name: Deploy Test (Main Branch)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.deploy_dev_from_main_push.outputs.overall_status == 'success'
    needs: deploy_dev_from_main_push # Depends on the orchestrator job for dev
    uses: InwardEcho/.github/.github/workflows/org-environment-orchestrator.yml@main
    with:
      environment_name: 'test'
      application_name: 'SampleApp'
      app_build_artifact_name_pattern: 'SampleApp-deployment-package'
      app_build_source_branch: 'main'

      iac_working_directory: './infra'
      iac_variables_file_path_pattern: './infra/{env}.tfvars'
      iac_backend_config_file_path_pattern: './infra/{env}.backend.hcl'
      iac_azure_credentials_secret_name: 'AZURE_CREDENTIALS_TF_INPUT'

      db_migration_efcore_project_path: './src/SampleApp.WebApp'
      db_connection_string_source: 'keyVault'
      db_azure_credentials_secret_name_for_kv: 'AZURE_CREDENTIALS_KV_INPUT'

      app_deploy_azure_credentials_secret_name: 'AZURE_CREDENTIALS_APP_INPUT'
      version_tag: 'main-${{ github.sha }}'
    secrets:
      AZURE_CREDENTIALS_TF_INPUT: ${{ secrets.AZURE_CREDENTIALS_TF_TEST }}
      AZURE_CREDENTIALS_KV_INPUT: ${{ secrets.AZURE_CREDENTIALS_KV_TEST }}
      AZURE_CREDENTIALS_APP_INPUT: ${{ secrets.AZURE_CREDENTIALS_APP_TEST }}

  deploy_prod_from_main_push:
    name: Deploy Production (Main Branch)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.deploy_test_from_main_push.outputs.overall_status == 'success'
    needs: deploy_test_from_main_push # Depends on the orchestrator job for test
    uses: InwardEcho/.github/.github/workflows/org-environment-orchestrator.yml@main
    with:
      environment_name: 'production'
      application_name: 'SampleApp'
      app_build_artifact_name_pattern: 'SampleApp-deployment-package'
      app_build_source_branch: 'main'

      iac_working_directory: './infra'
      iac_variables_file_path_pattern: './infra/{env}.tfvars'
      iac_backend_config_file_path_pattern: './infra/{env}.backend.hcl'
      iac_azure_credentials_secret_name: 'AZURE_CREDENTIALS_TF_INPUT'

      db_migration_efcore_project_path: './src/SampleApp.WebApp'
      db_connection_string_source: 'keyVault'
      db_azure_credentials_secret_name_for_kv: 'AZURE_CREDENTIALS_KV_INPUT'

      app_deploy_azure_credentials_secret_name: 'AZURE_CREDENTIALS_APP_INPUT'
      version_tag: 'main-${{ github.sha }}'
    secrets:
      AZURE_CREDENTIALS_TF_INPUT: ${{ secrets.AZURE_CREDENTIALS_TF_PROD }}
      AZURE_CREDENTIALS_KV_INPUT: ${{ secrets.AZURE_CREDENTIALS_KV_PROD }}
      AZURE_CREDENTIALS_APP_INPUT: ${{ secrets.AZURE_CREDENTIALS_APP_PROD }}