name: CI Build and Test SampleApp

on:
  push:
    branches: [ "**" ] # Build all branches
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test_dotnet:
    name: Build and Test .NET Application
    uses: InwardEcho/.github/workflows/org-build-test-dotnet.yml@main # Replace YourOrgName and ensure path/ref is correct
    with:
      dotnet-version: '8.0.x' # Or your target .NET version
      solution-path: './SampleApp.sln'
      build-configuration: 'Release'
      artifact-name-prefix: 'SampleApp'
      upload-artifacts: true
    secrets: inherit # If your org template needs secrets passed from the caller's context