name: SampleApp CI

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call_ci:
    name: Call Workflow
    uses: InwardEcho/workflow-templates/.github/workflows/fed.yml@main
    with:
      secrets: inherited
