name: SampleApp CD

on:
  workflow_dispatch:
    inputs:
      version_to_deploy:
        description: 'Version to deploy (e.g., 1.2.3 or 1.2.3-feature-xyz.5)'
        required: true
        type: string
      source_artifact_name:
        description: 'Name of the build artifact to download (e.g., release-1.2.3-app-package)'
        required: true
        type: string
      target_environment_type:
        description: 'Logical environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

permissions:
  contents: read
  id-token: write # Required for OIDC, if the unified workflow uses it.

# Concurrency control for this specific application's CD pipeline
concurrency:
  group: sampleapp-cd-${{ github.event.inputs.target_environment_type }}-${{ github.event.inputs.version_to_deploy }}
  cancel-in-progress: false

jobs:
  call_unified_cd:
    name: Call Unified CD Workflow for SampleApp
    # IMPORTANT: Replace the 'uses' path below with the correct reference to your unified workflow.
    # This could be:
    # - For a workflow in another repository: ORG/REPO/.github/workflows/unified-cd-workflow.yml@REF
    # - For a workflow in the same repository: ./.github/workflows/path/to/unified-cd-workflow.yml
    # The path provided in the prompt ('/Users/waqas.ittar/Desktop/source/workflow-templates/.github/workflows/unified-cd-workflow.yml')
    # is an absolute local path and cannot be used directly by GitHub Actions.
    uses: InwardEcho/workflow-templates/.github/workflows/unified-cd-workflow.yml@main # FIXME: Update this path

    with:
      # Core inputs from workflow_dispatch
      version_to_deploy: ${{ github.event.inputs.version_to_deploy }}
      source_artifact_name: ${{ github.event.inputs.source_artifact_name }}
      target_environment_type: ${{ github.event.inputs.target_environment_type }}

      # Application-specific parameters (adjust as per unified-cd-workflow.yml inputs)
      app_name: 'SampleApp'
      iac_working_directory: 'infra'
      # Example: if unified workflow expects patterns like '{env}.tfvars'
      # iac_var_file: '${{ github.event.inputs.target_environment_type }}.tfvars'
      # iac_backend_config_file: '${{ github.event.inputs.target_environment_type }}.backend.hcl'
      db_migration_project_path: 'src/SampleApp.WebApp/SampleApp.WebApp.csproj'
      # Add other inputs required by your unified-cd-workflow.yml

    secrets:
      # Pass all necessary secrets. The unified workflow must declare these as `secrets:` inputs.
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      AZURE_CREDENTIALS_APP_SERVICE: ${{ secrets.AZURE_CREDENTIALS_APP_SERVICE }}
      WORKFLOW_DISPATCH_PAT: ${{ secrets.WORKFLOW_DISPATCH_PAT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      # Add any other secrets the unified workflow might need.